### ISSUE TITLE
Help error

### ISSUE THREAD

**Issue by ziyatdinov** [go-reform/reform#22]
Help error

```
*main.Users

&main.Users{ID:1, Username:"zer", Password:"zer", Status:"active", Channel:"1", Created_at:1466744563, Last_activity_at:1466744563}panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x8bffa]

goroutine 1 [running]:
panic(0x3681c0, 0xc82000a0c0)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/go-reform/reform.(*Querier).Insert(0xc820015260, 0x6c28b0, 0xc82005e6c0, 0x0, 0x0)
        /Users/zer/golang/src/github.com/go-reform/reform/querier_commands.go:35 +0x70a
main.Conn()
        /Users/zer/dev/go/userapi/database.go:53 +0x7e6
main.main()
        /Users/zer/dev/go/userapi/main.go:22 +0x14
exit status 2

```

**Comment by AlekSi** [comment]
It's hard to guess without source code. What are you doing?

**Comment by ziyatdinov** [comment]
```
37	userst := &Users{
		ID:               1,
		Username:         "zer",
		Password:         "zer",
		Status:           "active",
		Channel:          "1",
		Created_at:       time.Now().Unix(),
		Last_activity_at: time.Now().Unix(),
	}

	var dialect reform.Dialect

	DB = reform.NewDB(db, dialect, nil)

	fmt.Printf("%T\n\n%#+v", userst, userst)

53	if err1 := DB.Insert(userst); err != nil {
		log.Fatal(err1)
	}

}
```

**Comment by AlekSi** [comment]
You are passing `nil` dialect. Please use `postgresql.Dialect`, `mysql.Dialect` or `sqlite3.Dialect`. See example here: https://godoc.org/gopkg.in/reform.v1#NewDB

**Comment by ziyatdinov** [comment]
ok good
