### ISSUE TITLE
panic: template: struct:27: illegal number syntax: "-"

### ISSUE THREAD

**Issue by xaionaro** [go-reform/reform#23]
Please help me to understand the reason of the next error:

```
$ go version
go version go1.5.1 linux/amd64
$ reform
panic: template: struct:27: illegal number syntax: "-"

goroutine 1 [running]:
text/template.Must(0x0, 0x7fafb582f028, 0xc82000aaf0, 0x0)
        /usr/lib/go/src/text/template/helper.go:23 +0x4b
main.init()
        /home/xaionaro/gocode/src/gopkg.in/reform.v1/reform/template.go:149 +0x212

$ cd /home/xaionaro/gocode/src/gopkg.in/reform.v1/reform; git log | head -1
commit d60dbfa976a39e47697f4038a37c7ae749030621

**Comment by xaionaro** [comment]
The same problem on golang 1.6.2.:
```
$ go version
go version go1.6.2 linux/amd64
```

**Comment by AlekSi** [comment]
That should not happen with 1.6. Please try to rebuild: `go install -a -v gopkg.in/reform.v1/...`

**Comment by xaionaro** [comment]
@AlekSi, sorry. Forgot to rebuild :/. Works on 1.6.
